const FETCH_ACTIONS = {
    PROGRESS: 'PROGRESS',
    SUCCESS: 'SUCCESS',
    ERROR: 'ERROR'
};

const CART_ACTIONS = {
    ADD_TO_CART: "ADD_TO_CART",
    REMOVE_FROM_CART: "REMOVE_FROM_CART",

}

export {FETCH_ACTIONS, CART_ACTIONS}